### PR TITLE
Register critical services in consul.

### LINKED ISSUE #552: Register critical services in consul.
Howdy, we currently have about 200 services in consul, and filtering them on only failed ones is a quick way for us to see that everything is up and running. However, containerpilot only registers a service after it has become healthy for the first time due to `job.sendHeartbeat()` being called in `onHealthCheckPassed`. 

If for some reason the service never gets healthy, the failed filter in consul does not give us that information. Currently, we have to manually search for the service that usually misbehave on startup.

It would be great to register a service as critical in consul in `onHealthCheckPassed`, but only if the services hasn't been seen before to not mess with the TTL.

### PR DESCRIPTION
**Pull request by eliasbrange**
Fixes #552 

This PR adds the functionality to register services in consul that never gets healthy to be able to filter on failed services in consul and see that they are misbehaving. 

I've added a method for registering a service with the status set to critical. This is called in `onHealthChechFailed`, but only if the service hasn't already been registered. I've also made some minor refactoring in `services/services.go`, i.e. having `MarkForMaintenance` call `Deregister` instead of the other way around.

### CODE REVIEW

File: jobs/jobs.go [hunk 1]
```diff
@@ -98,8 +98,16 @@ func FromConfigs(cfgs []*Config) []*Job {
...
+// registerUnhealthyService registers this Job's service with status set to
+// critical. Will only register the service if it does not already exist.
+func (job *Job) registerUnhealthyService() {
+	if job.Service != nil {
+		job.Service.RegisterUnhealthy()
+	}
+}
+
+// sendHeartbeat sends a heartbeat for this Job's service
+func (job *Job) sendHeartbeat() {
```
Comment (cheapRoc) [inline jobs/jobs.go]: I figured since the tests pass this isn't a problem but what were your thoughts on changing this from an exported method? `Job.SendHeartbeat` => `Job.sendHeartbeat`?

**Comment by cheapRoc** [comment]
Overall I think this is a great change. I can definitely imagine services that never come up to be critical state yet still registered in a service catalog. One question in the review otherwise I think we can include this in a next minor bump.

**Comment by cheapRoc** [comment]
Actually have a few more thoughts I'll post in the issue.

File: jobs/jobs.go (hunk 1 above)
Comment (eliasbrange) [reply jobs/jobs.go]: I had a hard time seeing how that method will be used outside of the job itself, but it's a small change so I can change it back if you'd like.

**Comment by eliasbrange** [comment]
Thanks for the feedback, I will try to address those thoughts in the issue.

**Comment by misterbisson** [comment]
@eliasbrange I'd love your feedback on @cheapRoc's suggestion about `initial_status` in https://github.com/joyent/containerpilot/issues/552, and if that works we'd also need to update the docs in this PR to correspond with the change .

File: discovery/service.go [hunk 2]
```diff
@@ -72,7 +101,7 @@ func (service *ServiceDefinition) registerService() error {
 			EnableTagOverride: service.EnableTagOverride,
 			Check: &api.AgentServiceCheck{
```
Comment (cheapRoc) [inline discovery/service.go]: After looking up that this is using Consul's `api.AgentServiceCheck` I believe the configuration option should be on the job level and _not_ within the health check. Optionally, we could expose the same `initial_status` option for all health checks independently... but I think that should be a future enhancement warranted from user requests for the feature.

File: jobs/config.go [hunk 3]
```diff
@@ -24,6 +24,7 @@ type Config struct {
 
 	// service discovery
 	Port              int           `mapstructure:"port"`
+	InitialStatus     string        `mapstructure:"initialStatus"`
```
Comment (cheapRoc) [inline jobs/config.go]: Let's call it `initial_status` (snake case), I don't believe we use lower camel case anywhere else. In Go we'll continue to use `InitialStatus`.

File: jobs/jobs.go [hunk 4]
```diff
@@ -98,13 +98,20 @@ func FromConfigs(cfgs []*Config) []*Job {
 	return jobs
 }
 
-// SendHeartbeat sends a heartbeat for this Job's service
-func (job *Job) SendHeartbeat() {
+// sendHeartbeat sends a heartbeat for this Job's service
+func (job *Job) sendHeartbeat() {
```
Comment (cheapRoc) [inline jobs/jobs.go]: Rename `sendHeartbeat` back to exported method `SendHeartbeat`.

File: jobs/jobs.go [hunk 5]
```diff
@@ -159,6 +166,9 @@ func (job *Job) Run(pctx context.Context, completedCh chan struct{}) {
 			completedCh <- struct{}{}
 		}()
 		for {
+			// Check if job's service has been registered. Doing it inside the event
+			// loop to retry if consul registration fails.
+			job.checkRegistration()
```
Comment (cheapRoc) [inline jobs/jobs.go]: 👍 Looks handy all by itself.

File: jobs/testdata/TestJobConfigServiceWithInitialStatus.json5 [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+    exec: "/bin/serviceA",
+    health: {
+      exec: "/bin/to/healthcheck/for/service/A.sh",
+      interval: 10,
+      ttl: 30,
+    },
+  },
+  {
+    name: "serviceB",
+    initialStatus: "invalid-value",
```
Comment (cheapRoc) [inline jobs/testdata/TestJobConfigServiceWithInitialStatus.json5]: Rename to `initial_status` here.

**Comment by cheapRoc** [comment]
Thank you again @eliasbrange for your continued support and patience.

**Comment by eliasbrange** [comment]
Reverted `SendHeartbeat` change and renamed to `initial_status` @cheapRoc .

File: jobs/config.go (hunk 3 above)
Comment (cheapRoc) [reply jobs/config.go]: Ah yes, you're right.

**Comment by cheapRoc** [comment]
I tested this PR with the following (rather convoluted) test rig using Fabio, `http-echo`, and the following configuration file.

```json5
{
  consul: "localhost:8500",
  logging: {
    level: "DEBUG",
    format: "text"
  },
  jobs: [
    {
      name: "foo",
      exec: "http-echo -listen=:8484 -text=hello",
      initial_status: "warning",
      tags: ["urlprefix-/foo"],
      port: 8484,
      health: {
        exec: "/usr/bin/curl -o /dev/null -sfI http://localhost:8484/",
        interval: 60,
        ttl: 60,
      },
    },
  ],
  control: {
    socket: "/tmp/cp.socket"
  }
}
```

I was able to verify that the Consul service check was initially set to `warning` status.

screen shot 2018-04-12 at 10 54 26 pm

With the health check set to `60` seconds I was able to wait and see the health check passing.

screen shot 2018-04-12 at 10 54 53 pm

Once again, I want to thank you for a wonderful addition to ContainerPilot @eliasbrange!

**Comment by eliasbrange** [comment]
Thanks for including it @cheapRoc. Will make it much easier for our monitoring!
